### ISSUE TITLE
How to use this with  Redis Connection pool?

### ISSUE THREAD

**Issue by lephyrius** [reswifq/redis-client-vapor#3]
How do I use it with Redis client pool?

```swift
let client = RedisClientPool(maxElementCount: 10 , factory: { () -> RedisClient in
                let tcpClient = try TCPClient(hostname: redisHost, port: UInt16(redisPort)!) // <- This can throw.
                return VaporRedisClient(tcpClient)   // <- This cannot return an optional.
            })
```

So how do I create a new VaporRedisClient that always succeeds?

**Comment by valeriomazzeo** [comment]
Hi @lephyrius thanks for the report.

This looks like an oversight on https://github.com/reswifq/pool/blob/master/Sources/Pool/Pool.swift

The factory method should probably be throwing.

**Comment by valeriomazzeo** [comment]
this is now fixed by https://github.com/reswifq/pool/commit/3b3ad5f98542ed42abe4bbea035591357519e5c5
